default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      workspace: "App/App.xcodeproj/project.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "Mitzo.ipa"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build only (no upload)"
  lane :build do
    build_app(
      workspace: "App/App.xcodeproj/project.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "Mitzo.ipa"
    )
  end
end
