/** Fixed native messages are matched in memory only. Never retain upstream text. */
export const nativeRoutingMessages = {
  'workspace routing discovery timed out': 'routing_timeout',
  'workspace routing discovery unauthorized (401)': 'routing_unauthorized',
  'workspace routing discovery failed': 'routing_failed',
  'selected workspace missing from routing discovery': 'routing_missing_workspace',
  'duplicate workspace in routing discovery': 'routing_duplicate_workspace',
  'workspace routing discovery missing backend origin': 'routing_missing_backend',
  'workspace routing discovery has invalid account routing override': 'routing_invalid_override',
  'workspace routing discovery must return an origin': 'routing_invalid_backend',
  'required ChatGPT backend conflicts with workspace routing': 'routing_backend_conflict',
  'invalid workspace backend URL': 'routing_invalid_backend',
  'workspace backend must use an HTTPS origin without credentials': 'routing_invalid_backend',
  'account changed during workspace routing discovery': 'routing_account_changed',
  'configuration changed during workspace routing discovery; retry account/read':
    'routing_config_changed',
  'failed to load workspace requirements': 'routing_requirements',
  'failed to reload workspace requirements': 'routing_requirements',
  'workspace routing requires a ChatGPT account id': 'routing_missing_account',
  'workspace routing discovery cancelled': 'routing_cancelled',
  'workspace routing discovery cancelled during shutdown': 'routing_cancelled',
  'workspace routing owner is unavailable': 'routing_owner_unavailable',
  'invalid model provider URL': 'routing_invalid_backend',
  'invalid ChatGPT backend URL': 'routing_invalid_backend',
  'invalid session ChatGPT backend URL': 'routing_invalid_backend',
  'ChatGPT backend changed; start a new thread before sending more content':
    'routing_config_changed',
} as const;
export type NativeRoutingFailure =
  (typeof nativeRoutingMessages)[keyof typeof nativeRoutingMessages];
export const nativeFailureCategories = [
  'routing_timeout',
  'routing_unauthorized',
  'routing_failed',
  'routing_missing_workspace',
  'routing_duplicate_workspace',
  'routing_missing_backend',
  'routing_invalid_override',
  'routing_invalid_backend',
  'routing_backend_conflict',
  'routing_account_changed',
  'routing_config_changed',
  'routing_requirements',
  'routing_missing_account',
  'routing_cancelled',
  'routing_owner_unavailable',
  'rpc_timeout',
  'rpc_connection',
  'rpc_protocol',
  'routing_identity_missing',
  'routing_identity_mismatch',
  'account_schema',
  'account_authentication',
  'thread_state',
  'provider_transport',
  'context_limit',
  'rate_limit',
  'authentication',
  'invalid_request',
  'unknown',
] as const;
export type NativeFailureCategory = (typeof nativeFailureCategories)[number];
