import { describe, expect, it } from 'vitest';
import { requestedIntegrationProviders } from '../integration-intent.js';

describe('requestedIntegrationProviders', () => {
  const grantable = ['google-workspace'];

  it.each([
    'look through my emails and Google Docs',
    'find the email Cat sent about my OKRs',
    'search Gmail for the launch note',
    'check my calendar for tomorrow',
    'use gws to list Drive files',
    'grant Google Workspace access',
    'send this via Gmail',
    'upload this to Google Drive',
    'create an event in Google Calendar',
    'reply to the email from Morgan',
    'search the Google Sheets budget',
    'open Google Docs',
    'In Gmail, find the message from Cat',
    'Google Calendar: create an event',
    'search Gmail for the API migration email',
    'find the parser incident email in Gmail',
    'allow Google Workspace access',
    'use Google Drive to inspect the budget',
    'schedule a meeting in Google Calendar',
    'edit my Google Doc',
    'download a file from Google Drive',
    'draft this in Gmail',
    'draft an email in Gmail',
    'uploading this to Google Drive',
    'uploaded this to Google Drive',
    'editing my Google Doc',
    'edited my Google Doc',
    'connecting Google Workspace',
    'connected Google Workspace',
    'use the Google Drive API to upload this file',
    'upload this via the Google Drive API',
    'download the report through the Google Drive API',
    'copy a file via the Google Drive API',
    'write this using the Google Docs API',
    'use the Google Drive API to list files',
    "Don't edit the code, just search Gmail for Cat",
    "I don't remember the subject, please search Gmail for Cat",
    "I can't recall the subject, please search Gmail for Cat",
    'Fix the Gmail handler and then search Gmail for Cat',
    'show my Gmail messages',
    'Explain how to use Gmail and then search Gmail for Cat',
    'Explain how to use Gmail and then show me how to use Google Drive and then search Gmail for Cat',
    'start by searching Gmail',
    'help me by checking my calendar',
    'I need to access my email',
    "What's on my calendar tomorrow?",
    'Any emails from Cat?',
    'show any emails from Cat',
    "show what's on my calendar",
    'Translate ‘search Gmail for Cat’ into Spanish, then search Gmail for Cat',
    'search Gmail for Cat but do not open Google Drive',
    'do not open Drive, but search Gmail for Cat',
    'check my email, but do not access my calendar',
    'check my calendar, but do not access my email',
    'find the email Cat sent. No, do not access my calendar.',
  ])('recognizes Google Workspace access intent in %j', (prompt) => {
    expect(requestedIntegrationProviders(prompt, grantable)).toEqual(['google-workspace']);
  });

  it.each([
    'draft an email to Cat',
    'editing code',
    'uploaded Google Drive documentation',
    'explain how Google Docs permissions work',
    'find the email parser bug',
    'inspect and fix the calendar UI',
    'write documentation for our email parser',
    'search the codebase; Google Drive is mentioned in the README',
    'summarize the Google Drive documentation and search the source code',
    'find the Gmail handler bug, then write a regression test',
    'Google Calendar API docs explain how to create an event',
    'search the repository for the Google Sheets component',
    'explain the Google Drive API',
    'fix the Gmail API client',
    'write Google Drive API documentation',
    'copy the Google Drive API docs into this repository',
    'do not access Gmail',
    'don’t access Gmail',
    "don't search my email",
    'never search my email',
    'without accessing Google Drive',
    'do not ever access Gmail',
    'never again search my email',
    'without directly accessing Google Drive',
    'avoid accessing Gmail',
    'refrain from using Google Drive',
    'prevent access to Gmail',
    'prevented access to Gmail',
    'stop accessing Gmail',
    'stopped accessing Gmail',
    'you can’t access Gmail',
    'you must not access Gmail',
    'you should not access Gmail',
    'you cannot access Gmail',
    "you can't access Gmail",
    'do not search or access Gmail',
    "please don't search or open Gmail",
    'do not search Gmail or open Google Drive',
    'do not search Gmail then open Google Drive',
    'do not search Gmail, access Gmail',
    'you must not search and then access Gmail',
    'explain how to use Gmail',
    'show me how to use Google Drive',
    'explain how to use Gmail and then show me how to use Google Drive',
    'what can I use Gmail for?',
    'search for Gmail references in the repo',
    'find Google Drive mentions in the source code',
    'search for the string "Gmail" in the repo',
    'find occurrences of Google Drive',
    'search Gmail usages in the codebase',
    'what is a calendar?',
    'any email parser errors?',
    'Translate ‘search Gmail for Cat’ into Spanish',
    'Search Gmail, but actually do not access Gmail',
    "Translate 'search Gmail for Cat' into Spanish",
    'search Gmail, but do not access Google Mail',
    'search Google Mail, but do not access Gmail',
    'search Gmail, but do not access Google Workspace',
    'check my email, but do not access my email',
    'search Gmail. Do not access my email',
    'check my drive, but do not access my drive',
    'open my documents, but do not access my documents',
    'find the email Cat sent. No, do not access my email.',
    'reply to the email from Morgan, but do not access my email',
    'check the calendar for tomorrow. No, do not access my calendar.',
    'do not show any emails from Cat',
    "do not show what's on my calendar",
    'show any emails from Cat, but do not show any emails from Morgan',
  ])('does not grant account access for content or technical work in %j', (prompt) => {
    expect(requestedIntegrationProviders(prompt, grantable)).toEqual([]);
  });

  it.each([
    'do not search the repo; search Gmail for Cat',
    'do not search the repo; then search Gmail for Cat',
    'search Gmail for Cat but do not open Google Drive',
    'do not open Drive, but search Gmail for Cat',
    'stop discussing Gmail and search Gmail for Cat',
    "do not show any emails from Cat, but show what's on my calendar",
  ])('keeps affirmative access intent in a different clause for %j', (prompt) => {
    expect(requestedIntegrationProviders(prompt, grantable)).toEqual(['google-workspace']);
  });

  it('never returns a provider that is not configured as grantable', () => {
    expect(requestedIntegrationProviders('search Gmail', [])).toEqual([]);
  });

  it('handles a large repeated clause without expanding action/resource pairs', () => {
    const prompt = Array.from({ length: 12_000 }, () => 'search Gmail for Cat').join(' ');
    expect(requestedIntegrationProviders(prompt, grantable)).toEqual(['google-workspace']);
  });
});
