import { it, expect } from 'vitest';
import { verifyFrozenKeyGateway } from '../../scripts/lib/staging-key-material.mjs';
import { mkdtempSync, chmodSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
// Use a synthetic fixture from the literal historical schema, with no process,
// provider or real model. Expected contents are not generated by the verifier.
function fixture() {
  const parent = mkdtempSync(join(tmpdir(), 'key-material-'));
  chmodSync(parent, 0o700);
  return { parent };
}
it('rejects unrecognized material before reading keys', () => {
  const f = fixture();
  try {
    writeFileSync(join(f.parent, 'unexpected'), 'x');
    expect(() => verifyFrozenKeyGateway({}, f.parent)).toThrow();
  } finally {
    rmSync(f.parent, { recursive: true });
  }
});

it('rejects a configured launch without the mandatory gateway_jwt table', () => {
  const f = fixture();
  try {
    writeFileSync(join(f.parent, 'gateway.toml'), '[openshell.gateway]\n');
    expect(() => verifyFrozenKeyGateway({ tls: {}, jwt: {} }, f.parent)).toThrow();
  } finally {
    rmSync(f.parent, { recursive: true });
  }
});
