version: 1
filesystem_policy:
  include_workdir: false
  read_only: [/usr, /lib, /proc, /dev/urandom, /etc]
  read_write: [/tmp, /dev/null]
landlock:
  compatibility: best_effort
network_policies:
  jira_identity:
    name: jira-identity-readonly
    endpoints:
      - host: api.atlassian.com
        port: 443
        protocol: rest
        enforcement: enforce
        tls: terminate
        rules:
          - allow: { method: GET, path: /ex/jira/2b9e35e3-6bd3-4cec-b838-f4249ee02432/rest/api/3/myself }
    binaries:
      - { path: /usr/bin/python3 }
